DEFAULT_COLUMNS = 5
DEFAULT_SCALE   = 3
WINDOW_TITLE    = "PDF417 Studio"

PREVIEW_MAX_WIDTH  = 560
PREVIEW_MAX_HEIGHT = 220

EXPORT_IMG_WIDTH  = PREVIEW_MAX_WIDTH
EXPORT_IMG_HEIGHT = PREVIEW_MAX_HEIGHT

AAMVA_MAX_WIDTH_MM   = 75.565
AAMVA_MAX_HEIGHT_MM  = 38.100

AAMVA_X_MIN_MM   = 0.170
AAMVA_X_MAX_MM   = 0.380
AAMVA_X_MIN_MILS = 6.6
AAMVA_X_MAX_MILS = 15.0

AAMVA_Y_X_RATIO_MIN  = 3

AAMVA_QUIET_ZONE_MIN = 1
AAMVA_QUIET_ZONE_REC = 2

AAMVA_PROHIBITED = ("MicroPDF417", "Truncated PDF417")